/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package printingjalpa;

import java.awt.Color;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author samue
 */
public class JWinMain extends javax.swing.JFrame {
    private ImageIcon getResizedIcon(Icon icon,int width,int height){
        ImageIcon ico = (ImageIcon)icon;
        Image ic = ico.getImage();
        ic = ic.getScaledInstance(width,height,Image.SCALE_SMOOTH);
        return new ImageIcon(ic);
    }
    private void limpiarTamañosSelected(){
        for(int i=0;i<3;i++){
            tamañosSelected[i]=false;
        }
        iconCh.setBorder(null);
        iconM.setBorder(null);
        iconGR.setBorder(null);
    }
    public void limpiarColoresC(){
        azulC.setSelected(false);
        rosaC.setSelected(false);
        rojoC.setSelected(false);
        cieloC.setSelected(false);
        blancoC.setSelected(false);
        mentaC.setSelected(false);
        lilaC.setSelected(false);
        verdeC.setSelected(false);
        // Look and Feel //
        azulC.setBorder(null);
        rosaC.setBorder(null);
        rojoC.setBorder(null);
        cieloC.setBorder(null);
        blancoC.setBorder(null);
        mentaC.setBorder(null);
        lilaC.setBorder(null);
        verdeC.setBorder(null);
    }
    public void limpiarColoresT(){
        negroT.setSelected(false);
        blancoT.setSelected(false);
        goldT.setSelected(false);
        silverT.setSelected(false);
        // Look and Feel //
        negroT.setBorder(null);
        blancoT.setBorder(null);
        goldT.setBorder(null);
        silverT.setBorder(null);
    }
    GraphicsEnvironment g = GraphicsEnvironment.getLocalGraphicsEnvironment();
    /**
     * Creates new form JWinMain
     */
    public JWinMain() {
        this.hover = new LineBorder(Color.gray);
        this.selection = new LineBorder(Color.orange);
        tamañosSelected = new boolean[]{false,false,false};
        initComponents();
        iconCh.setIcon(getResizedIcon(iconCh.getIcon(),iconCh.getWidth(),iconCh.getHeight()));
        iconM.setIcon(getResizedIcon(iconM.getIcon(),iconM.getWidth(),iconM.getHeight()));
        iconGR.setIcon(getResizedIcon(iconGR.getIcon(),iconGR.getWidth(),iconGR.getHeight()));
        for(String s : g.getAvailableFontFamilyNames()){
            comboFuente.addItem(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        iconGR = new javax.swing.JLabel();
        iconCh = new javax.swing.JLabel();
        iconM = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rosaC = new printingjalpa.JPanelCircle();
        rojoC = new printingjalpa.JPanelCircle();
        azulC = new printingjalpa.JPanelCircle();
        cieloC = new printingjalpa.JPanelCircle();
        verdeC = new printingjalpa.JPanelCircle();
        lilaC = new printingjalpa.JPanelCircle();
        mentaC = new printingjalpa.JPanelCircle();
        blancoC = new printingjalpa.JPanelCircle();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        comboFuente = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comboTamaño = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        textoEst = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        blancoT = new printingjalpa.JPanelCircle();
        negroT = new printingjalpa.JPanelCircle();
        goldT = new printingjalpa.JPanelCircle();
        silverT = new printingjalpa.JPanelCircle();
        jPanel6 = new javax.swing.JPanel();
        preImagen = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAñadir = new javax.swing.JButton();
        imagenSel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        comboEntrega = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Termos Jalpa V0.0.1beta");
        setResizable(false);

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Termos Jalpa!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Tamaño del Termo:");

        iconGR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TermoGR.png"))); // NOI18N
        iconGR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconGRMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iconGRMouseEntered(evt);
            }
        });

        iconCh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TermoCH.png"))); // NOI18N
        iconCh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconChMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iconChMouseEntered(evt);
            }
        });

        iconM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TermoM.png"))); // NOI18N
        iconM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconMMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iconMMouseEntered(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Chico");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Mediano");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Grande");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel7))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(iconCh, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(iconM, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(iconGR, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel8)
                                .addGap(90, 90, 90)
                                .addComponent(jLabel9)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconGR, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconM, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconCh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Color del Termo:");

        rosaC.setForeground(new java.awt.Color(246, 176, 203));
        rosaC.setToolTipText("Rosa");
        rosaC.setMinimumSize(new java.awt.Dimension(20, 20));
        rosaC.setPreferredSize(new java.awt.Dimension(30, 30));
        rosaC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rosaCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout rosaCLayout = new javax.swing.GroupLayout(rosaC);
        rosaC.setLayout(rosaCLayout);
        rosaCLayout.setHorizontalGroup(
            rosaCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        rosaCLayout.setVerticalGroup(
            rosaCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        rojoC.setForeground(new java.awt.Color(255, 0, 51));
        rojoC.setToolTipText("Rojo");
        rojoC.setMinimumSize(new java.awt.Dimension(20, 20));
        rojoC.setPreferredSize(new java.awt.Dimension(30, 30));
        rojoC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rojoCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout rojoCLayout = new javax.swing.GroupLayout(rojoC);
        rojoC.setLayout(rojoCLayout);
        rojoCLayout.setHorizontalGroup(
            rojoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        rojoCLayout.setVerticalGroup(
            rojoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        azulC.setForeground(new java.awt.Color(51, 0, 255));
        azulC.setToolTipText("Azul");
        azulC.setMinimumSize(new java.awt.Dimension(20, 20));
        azulC.setPreferredSize(new java.awt.Dimension(30, 30));
        azulC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                azulCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout azulCLayout = new javax.swing.GroupLayout(azulC);
        azulC.setLayout(azulCLayout);
        azulCLayout.setHorizontalGroup(
            azulCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        azulCLayout.setVerticalGroup(
            azulCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        cieloC.setForeground(new java.awt.Color(153, 204, 255));
        cieloC.setToolTipText("Cielo");
        cieloC.setMinimumSize(new java.awt.Dimension(20, 20));
        cieloC.setPreferredSize(new java.awt.Dimension(30, 30));
        cieloC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cieloCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout cieloCLayout = new javax.swing.GroupLayout(cieloC);
        cieloC.setLayout(cieloCLayout);
        cieloCLayout.setHorizontalGroup(
            cieloCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        cieloCLayout.setVerticalGroup(
            cieloCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        verdeC.setForeground(new java.awt.Color(102, 255, 102));
        verdeC.setToolTipText("Verde");
        verdeC.setMinimumSize(new java.awt.Dimension(20, 20));
        verdeC.setPreferredSize(new java.awt.Dimension(30, 30));
        verdeC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verdeCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout verdeCLayout = new javax.swing.GroupLayout(verdeC);
        verdeC.setLayout(verdeCLayout);
        verdeCLayout.setHorizontalGroup(
            verdeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        verdeCLayout.setVerticalGroup(
            verdeCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        lilaC.setForeground(new java.awt.Color(204, 153, 255));
        lilaC.setToolTipText("Lila");
        lilaC.setMinimumSize(new java.awt.Dimension(20, 20));
        lilaC.setPreferredSize(new java.awt.Dimension(30, 30));
        lilaC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lilaCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout lilaCLayout = new javax.swing.GroupLayout(lilaC);
        lilaC.setLayout(lilaCLayout);
        lilaCLayout.setHorizontalGroup(
            lilaCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        lilaCLayout.setVerticalGroup(
            lilaCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        mentaC.setForeground(new java.awt.Color(153, 255, 204));
        mentaC.setToolTipText("Menta");
        mentaC.setMinimumSize(new java.awt.Dimension(20, 20));
        mentaC.setPreferredSize(new java.awt.Dimension(30, 30));
        mentaC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mentaCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mentaCLayout = new javax.swing.GroupLayout(mentaC);
        mentaC.setLayout(mentaCLayout);
        mentaCLayout.setHorizontalGroup(
            mentaCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        mentaCLayout.setVerticalGroup(
            mentaCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        blancoC.setForeground(new java.awt.Color(255, 255, 255));
        blancoC.setToolTipText("Blanco");
        blancoC.setMinimumSize(new java.awt.Dimension(20, 20));
        blancoC.setPreferredSize(new java.awt.Dimension(30, 30));
        blancoC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blancoCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout blancoCLayout = new javax.swing.GroupLayout(blancoC);
        blancoC.setLayout(blancoCLayout);
        blancoCLayout.setHorizontalGroup(
            blancoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        blancoCLayout.setVerticalGroup(
            blancoCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rosaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rojoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(azulC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cieloC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(verdeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lilaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mentaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(blancoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rosaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rojoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(azulC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cieloC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verdeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lilaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mentaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blancoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Texto estampado en el termo:");

        comboFuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFuenteActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Fuente");

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Tamaño");

        comboTamaño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 cm", "4 cm", "6 cm", "10 cm", "12 cm" }));
        comboTamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTamañoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Texto estampado");

        textoEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoEstActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Color");

        blancoT.setForeground(new java.awt.Color(255, 255, 255));
        blancoT.setToolTipText("Blanco");
        blancoT.setPreferredSize(new java.awt.Dimension(30, 30));
        blancoT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blancoTMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout blancoTLayout = new javax.swing.GroupLayout(blancoT);
        blancoT.setLayout(blancoTLayout);
        blancoTLayout.setHorizontalGroup(
            blancoTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        blancoTLayout.setVerticalGroup(
            blancoTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        negroT.setForeground(new java.awt.Color(0, 0, 0));
        negroT.setToolTipText("Negro");
        negroT.setPreferredSize(new java.awt.Dimension(30, 30));
        negroT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                negroTMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout negroTLayout = new javax.swing.GroupLayout(negroT);
        negroT.setLayout(negroTLayout);
        negroTLayout.setHorizontalGroup(
            negroTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        negroTLayout.setVerticalGroup(
            negroTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        goldT.setForeground(new java.awt.Color(204, 204, 0));
        goldT.setToolTipText("Dorado");
        goldT.setPreferredSize(new java.awt.Dimension(30, 30));
        goldT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goldTMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout goldTLayout = new javax.swing.GroupLayout(goldT);
        goldT.setLayout(goldTLayout);
        goldTLayout.setHorizontalGroup(
            goldTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        goldTLayout.setVerticalGroup(
            goldTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        silverT.setForeground(new java.awt.Color(204, 204, 204));
        silverT.setToolTipText("Plateado");
        silverT.setPreferredSize(new java.awt.Dimension(30, 30));
        silverT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                silverTMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout silverTLayout = new javax.swing.GroupLayout(silverT);
        silverT.setLayout(silverTLayout);
        silverTLayout.setHorizontalGroup(
            silverTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        silverTLayout.setVerticalGroup(
            silverTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(0, 19, Short.MAX_VALUE)
                                        .addComponent(comboTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(117, 117, 117)
                                        .addComponent(blancoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(negroT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(goldT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(silverT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(73, 73, 73))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(104, 104, 104))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(comboFuente, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(textoEst, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoEst)
                            .addComponent(comboFuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(goldT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(silverT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(blancoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(negroT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Previsualización.");

        btnAñadir.setText("Añadir Imagen");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAñadir))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(preImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(imagenSel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imagenSel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(41, 41, 41)
                        .addComponent(preImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(btnAñadir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Datos del cliente");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Nombre: ");

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Teléfono:");

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Entrega en");

        comboEntrega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tienda Jalpa", "Tienda Calvillo", "Taller Jalpa" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombre)
                            .addComponent(telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(comboEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        btnGuardar.setText("Guardar Pedido");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboTamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTamañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTamañoActionPerformed

    private void textoEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoEstActionPerformed

    private void iconChMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconChMouseEntered
        
    }//GEN-LAST:event_iconChMouseEntered

    private void iconMMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_iconMMouseEntered

    private void iconGRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconGRMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_iconGRMouseEntered

    private void iconChMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconChMouseClicked
        limpiarTamañosSelected();
        tamañosSelected[0] = true;
        iconCh.setBorder(selection);
        preImagen.setIcon(getResizedIcon(iconCh.getIcon(),
                preImagen.getWidth(),preImagen.getHeight()));
    }//GEN-LAST:event_iconChMouseClicked

    private void iconMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMMouseClicked
        limpiarTamañosSelected();
        tamañosSelected[1] = true;
        iconM.setBorder(selection);
        preImagen.setIcon(getResizedIcon(iconM.getIcon(),
                preImagen.getWidth(),preImagen.getHeight()));
    }//GEN-LAST:event_iconMMouseClicked

    private void iconGRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconGRMouseClicked
        limpiarTamañosSelected();
        tamañosSelected[2] = true;
        iconGR.setBorder(selection);
        iconGR.setBorder(selection);
        preImagen.setIcon(getResizedIcon(iconGR.getIcon(),
                preImagen.getWidth(),preImagen.getHeight()));
    }//GEN-LAST:event_iconGRMouseClicked

    private void rosaCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rosaCMouseClicked
        limpiarColoresC();
        rosaC.setSelected(true);
        rosaC.setBorder(selection);
    }//GEN-LAST:event_rosaCMouseClicked

    private void rojoCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rojoCMouseClicked
        limpiarColoresC();
        rojoC.setSelected(true);
        rojoC.setBorder(selection);
    }//GEN-LAST:event_rojoCMouseClicked

    private void azulCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_azulCMouseClicked
        limpiarColoresC();
        azulC.setSelected(true);
        azulC.setBorder(selection);
    }//GEN-LAST:event_azulCMouseClicked

    private void cieloCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cieloCMouseClicked
        limpiarColoresC();
        cieloC.setSelected(true);
        cieloC.setBorder(selection);
    }//GEN-LAST:event_cieloCMouseClicked

    private void verdeCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verdeCMouseClicked
        limpiarColoresC();
        verdeC.setSelected(true);
        verdeC.setBorder(selection);
    }//GEN-LAST:event_verdeCMouseClicked

    private void lilaCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lilaCMouseClicked
        limpiarColoresC();
        lilaC.setSelected(true);
        lilaC.setBorder(selection);
    }//GEN-LAST:event_lilaCMouseClicked

    private void mentaCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mentaCMouseClicked
        limpiarColoresC();
        mentaC.setSelected(true);
        mentaC.setBorder(selection);
    }//GEN-LAST:event_mentaCMouseClicked

    private void blancoCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blancoCMouseClicked
        limpiarColoresC();
        blancoC.setSelected(true);
        blancoC.setBorder(selection);
    }//GEN-LAST:event_blancoCMouseClicked

    private void blancoTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blancoTMouseClicked
        limpiarColoresT();
        blancoT.setSelected(true);
        blancoT.setBorder(selection);
    }//GEN-LAST:event_blancoTMouseClicked

    private void negroTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_negroTMouseClicked
        limpiarColoresT();
        negroT.setSelected(true);
        negroT.setBorder(selection);
    }//GEN-LAST:event_negroTMouseClicked

    private void goldTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goldTMouseClicked
        limpiarColoresT();
        goldT.setSelected(true);
        goldT.setBorder(selection);
    }//GEN-LAST:event_goldTMouseClicked

    private void silverTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_silverTMouseClicked
        limpiarColoresT();
        silverT.setSelected(true);
        silverT.setBorder(selection);
    }//GEN-LAST:event_silverTMouseClicked

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        JFileChooser jFile = new JFileChooser("src/Imagenes");
        jFile.setFileFilter(new FileFilter(){
            @Override
            public boolean accept(File f) {
                if(f.isDirectory()){
                    return true;
                }
                String fileName = f.getName();
                return fileName.contains(".jpg")||
                        fileName.contains("jpeg")||
                        fileName.contains(".png");
            }

            @Override
            public String getDescription() {
                return "Imagenes";
            }
            
        });
        int option = jFile.showOpenDialog(this);
        if(option == JFileChooser.APPROVE_OPTION){
            ImageIcon im = new ImageIcon(jFile.getSelectedFile().getAbsolutePath());
            im = getResizedIcon(im,imagenSel.getWidth(),imagenSel.getHeight());
            imagenSel.setIcon(im);
        }
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        JOptionPane.showMessageDialog(null,"Este es solo un prototipo no funcional","Prototipo No Funcional"
                ,JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void comboFuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFuenteActionPerformed
        
    }//GEN-LAST:event_comboFuenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JWinMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JWinMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JWinMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JWinMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JWinMain().setVisible(true);
            }
        });
    }
    //Variables//
    private LineBorder selection;
    private LineBorder hover;
    private boolean[] tamañosSelected;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private printingjalpa.JPanelCircle azulC;
    private printingjalpa.JPanelCircle blancoC;
    private printingjalpa.JPanelCircle blancoT;
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnGuardar;
    private printingjalpa.JPanelCircle cieloC;
    private javax.swing.JComboBox<String> comboEntrega;
    private javax.swing.JComboBox<String> comboFuente;
    private javax.swing.JComboBox<String> comboTamaño;
    private printingjalpa.JPanelCircle goldT;
    private javax.swing.JLabel iconCh;
    private javax.swing.JLabel iconGR;
    private javax.swing.JLabel iconM;
    private javax.swing.JLabel imagenSel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private printingjalpa.JPanelCircle lilaC;
    private printingjalpa.JPanelCircle mentaC;
    private printingjalpa.JPanelCircle negroT;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel preImagen;
    private printingjalpa.JPanelCircle rojoC;
    private printingjalpa.JPanelCircle rosaC;
    private printingjalpa.JPanelCircle silverT;
    private javax.swing.JTextField telefono;
    private javax.swing.JTextField textoEst;
    private printingjalpa.JPanelCircle verdeC;
    // End of variables declaration//GEN-END:variables
}
